// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EditBox: typeof import('./src/components/EditBox.vue')['default']
    EditBoxBoss: typeof import('./src/components/editBox/EditBoxBoss.vue')['default']
    EditBoxChange: typeof import('./src/components/editBox/EditBoxChange.vue')['default']
    EditBoxFor: typeof import('./src/components/editBox/EditBoxFor.vue')['default']
    EditBoxOther: typeof import('./src/components/editBox/EditBoxOther.vue')['default']
    EditBoxSkill: typeof import('./src/components/editBox/EditBoxSkill.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElNumberinput: typeof import('element-plus/es')['ElNumberinput']
    ElNumberInput: typeof import('element-plus/es')['ElNumberInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTag: typeof import('element-plus/es')['ElTag']
    PreviewBox: typeof import('./src/components/PreviewBox.vue')['default']
  }
}
